import 'package:design_coverage/src/design_coverage_entry.dart';

class DesignCoverageMarkdownRenderer {
  static const String _generatorCommand =
      'dart run design_coverage:generate_design_coverage';

  const DesignCoverageMarkdownRenderer();

  String render(List<DesignCoverageEntry> entries) {
    final buffer = StringBuffer()
      ..writeln('# Design Coverage')
      ..writeln()
      ..writeln(
        'This document is generated automatically from '
        '`@DesignComponent` annotations in the codebase.',
      )
      ..writeln()
      ..writeln(
        'It shows which Flutter widgets are linked to design components.',
      )
      ..writeln()
      ..writeln('---')
      ..writeln();

    if (entries.isEmpty) {
      _writeEmptyState(buffer);
    } else {
      _writeCategories(buffer, entries);
    }

    _writeSummary(buffer, entries);

    return '${buffer.toString().trimRight()}\n';
  }

  void _writeEmptyState(StringBuffer buffer) {
    buffer
      ..writeln('No annotated components found.')
      ..writeln()
      ..writeln('---')
      ..writeln();
  }

  void _writeCategories(
    StringBuffer buffer,
    List<DesignCoverageEntry> entries,
  ) {
    final entriesByCategory = <String, List<DesignCoverageEntry>>{};

    for (final entry in entries) {
      entriesByCategory
          .putIfAbsent(entry.category, () => <DesignCoverageEntry>[])
          .add(entry);
    }

    final categories = entriesByCategory.keys.toList();

    for (final category in categories) {
      final categoryEntries = entriesByCategory[category]!;

      buffer
        ..writeln('## $category')
        ..writeln()
        ..writeln('| Design Component | Design URL | Flutter Widget | Notes |')
        ..writeln('| ---------------- | ---------- | -------------- | ----- |');

      for (final entry in categoryEntries) {
        buffer.writeln(_buildRow(entry));
      }

      buffer
        ..writeln()
        ..writeln('---')
        ..writeln();
    }
  }

  String _buildRow(DesignCoverageEntry entry) {
    final notes = entry.description ?? '-';
    final designCell = '[Open](${entry.designUrl})';
    final widgetCell = '[`${entry.className}`](${entry.sourceDocUrl})';

    return '| ${_escape(entry.displayName)} | $designCell | $widgetCell | '
        '${_escape(notes)} |';
  }

  void _writeSummary(StringBuffer buffer, List<DesignCoverageEntry> entries) {
    final categories = <String>{};
    final designUrls = <String>{};

    for (final entry in entries) {
      categories.add(entry.category);
      designUrls.add(entry.designUrl);
    }

    final categoriesCount = categories.length;
    final designUrlsCount = designUrls.length;

    buffer
      ..writeln('## Summary')
      ..writeln()
      ..writeln('| Metric | Value |')
      ..writeln('| ------ | ----- |')
      ..writeln('| Total annotated components | ${entries.length} |')
      ..writeln('| Total categories | $categoriesCount |')
      ..writeln('| Total design URLs | $designUrlsCount |')
      ..writeln()
      ..writeln('---')
      ..writeln()
      ..writeln('Generated by `$_generatorCommand`.');
  }

  String _escape(String value) {
    return value.replaceAll('|', r'\|').replaceAll('\n', ' ');
  }
}
