name: design_coverage
description: Generator package for design coverage markdown output.
publish_to: none

version: 0.1.0

environment:
  sdk: ^3.11.1

dependencies:
  analyzer: ^8.4.0
  path: ^1.9.1
  design_coverage_annotation:
    git:
      url: https://github.com/valeriinov/design_coverage.git
      path: packages/design_coverage_annotation
      ref: 0.1.0
